name: Contracts CI/CD
on: 
  push:
    paths:
      - packages/hardhat/contracts/**/*.sol
jobs:
  xdai:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Cache yarn modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: yarn-${{ hashFiles('yarn.lock') }}

    - name: Cache contracts
      uses: actions/cache@v2
      with:
        path: |
          packages/*/cache
          packages/*/artifacts
          packages/*/typechain
          ~/.cache/hardhat-nodejs/
        key: contracts-${{ hashFiles('packages/*/contracts/**/*.sol') }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Deploy veneto garden
      env:
        XDAI_NODE: ${{ secrets.XDAI_NODE }}
      run: HARDHAT_FORK=xdai HARDHAT_FORK_URL="$XDAI_NODE" HNY_HOLDER=0xc447384681aDfBb6AF5BB2D4a0e4DE05135ebFED yarn new:garden:veneto

    - name: Deploy boboli garden
      env:
        XDAI_NODE: ${{ secrets.XDAI_NODE }}
      run: HARDHAT_FORK=xdai HARDHAT_FORK_URL="$XDAI_NODE" HNY_HOLDER=0xc447384681aDfBb6AF5BB2D4a0e4DE05135ebFED yarn new:garden:boboli

  
  polygon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Cache yarn modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: yarn-${{ hashFiles('yarn.lock') }}

    - name: Cache contracts
      uses: actions/cache@v2
      with:
        path: |
          packages/*/cache
          packages/*/artifacts
          packages/*/typechain
          ~/.cache/hardhat-nodejs/
        key: contracts-${{ hashFiles('packages/*/contracts/**/*.sol') }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Deploy veneto garden
      env:
        POLYGON_NODE: ${{ secrets.POLYGON_NODE }}
      run: HARDHAT_FORK=polygon HARDHAT_FORK_URL="$POLYGON_NODE" HNY_HOLDER=0x625236038836CecC532664915BD0399647E7826b yarn new:garden:veneto

    - name: Deploy boboli garden
      run: HARDHAT_FORK=polygon HARDHAT_FORK_URL="$POLYGON_NODE" HNY_HOLDER=0x625236038836CecC532664915BD0399647E7826b yarn new:garden:boboli
  
  rinkeby:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Cache yarn modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: yarn-${{ hashFiles('yarn.lock') }}

    - name: Cache contracts
      uses: actions/cache@v2
      with:
        path: |
          packages/*/cache
          packages/*/artifacts
          packages/*/typechain
          ~/.cache/hardhat-nodejs/
        key: contracts-${{ hashFiles('packages/*/contracts/**/*.sol') }}
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build contracts
      run: yarn compile

    - name: Deploy veneto garden
      env:
        RINKEBY_NODE: ${{ secrets.RINKEBY_NODE }}
      run: HARDHAT_FORK=polygon HARDHAT_FORK_URL="$RINKEBY_NODE" HNY_HOLDER=0x4355a2cdec902C372F404007114bbCf2C65A3eb0 yarn new:garden:veneto

    - name: Deploy boboli garden
      env:
        RINKEBY_NODE: ${{ secrets.RINKEBY_NODE }}
      run: HARDHAT_FORK=polygon HARDHAT_FORK_URL="$RINKEBY_NODE" HNY_HOLDER=0x4355a2cdec902C372F404007114bbCf2C65A3eb0 yarn new:garden:boboli
